# Use the official Node.js image
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm i -g pnpm
RUN pnpm install

# Copy the rest of the application code
COPY * .

# Expose the development port
EXPOSE ${DWS_INT_WEBAPP_PORT}

# # Start the Vite development server
CMD ["pnpm", "run", "dev"]
