name: "dws_docker_infrastructure"
services:
  dws-exposed-webapp:
    build:
      context: ../apps/frontend/dws-exposed-webapp
      dockerfile: ${DWS_EXT_WEBAPP_DOCKERFILE}
    ports:
      - "${DWS_EXT_WEBAPP_PORT}:${DWS_EXT_WEBAPP_PORT}"
    volumes:
      - ../apps/frontend/dws-exposed-webapp:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=${DWS_EXT_WEBAPP_PORT}
      - NEXT_PUBLIC_API_PORT=${DWS_GO_PORT}
      - NEXT_PUBLIC_API_HOST=${DWS_GO_HOST}
      - NEXT_PUBLIC_API_HOST_PREFIX=${DWS_GO_HOST_PREFIX}

  dws-internal-webapp:
    build:
      context: ../apps/frontend/dws-internal-webapp
      dockerfile: ${DWS_INT_WEBAPP_DOCKERFILE}
    ports:
      - "${DWS_INT_WEBAPP_PORT}:${DWS_INT_WEBAPP_PORT}"
    volumes:
      - ../apps/frontend/dws-internal-webapp:/app
      - /app/node_modules
    environment:
      - PORT=${DWS_INT_WEBAPP_PORT}
      - VITE_PUBLIC_API_PORT=${DWS_GO_PORT}
      - VITE_PUBLIC_API_HOST=${DWS_GO_HOST}
      - VITE_PUBLIC_API_HOST_PREFIX=${DWS_GO_HOST_PREFIX}
      - CHOKIDAR_USEPOLLING=true

  dws-api-gateway:
    build:
      context: ../apps/backend/dws-api-gateway
      dockerfile: ${DWS_GO_DOCKERFILE}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${DWS_GO_PORT}/health" ]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - "${DWS_GO_PORT}:${DWS_GO_PORT}"
    volumes:
      - ../apps/backend/dws-api-gateway:/app
    environment:
      - ENV=${DWS_GO_ENV}
      - PORT=${DWS_GO_PORT}
      - DB_HOST=${DWS_DB_HOST}
      - DB_PORT=${DWS_DB_PORT}
      - DB_USERNAME=${DWS_DB_USERNAME}
      - DB_PASSWORD=${DWS_DB_ROOT_PASSWORD}
      - ML_PORT=${DWS_ML_PORT}
      - ML_HOST=${DWS_ML_HOST}
    depends_on:
      - dws_mongodb
      - dws-ml-service
    networks:
      - dws-network

  dws-ml-service:
    build:
      context: ../apps/backend/dws-ml-service
      dockerfile: ${DWS_ML_DOCKERFILE}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${DWS_ML_PORT}/health" ]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - "${DWS_ML_PORT}:${DWS_ML_PORT}"
    volumes:
      - ../apps/backend/dws-ml-service:/app
    environment:
      - PYTHON_ENV=${DWS_ML_ENV}
      - PORT=${DWS_ML_PORT}
      - DB_HOST=${DWS_DB_HOST}
      - DB_PORT=${DWS_DB_PORT}
      - DB_USERNAME=${DWS_DB_USERNAME}
      - DB_PASSWORD=${DWS_DB_ROOT_PASSWORD}
    networks:
      - dws-network

  dws_mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DWS_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DWS_DB_ROOT_PASSWORD}
    ports:
      - ${DWS_DB_PORTS}
    volumes:
      - mongo_volume_dws:/data/db
    networks:
      - dws-network

networks:
  dws-network:


volumes:
  mongo_volume_dws:
