// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/dws_ml_service.proto

package dws

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriftwoodSearchService_SearchDriftwood_FullMethodName = "/dws.DriftwoodSearchService/SearchDriftwood"
)

// DriftwoodSearchServiceClient is the client API for DriftwoodSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Driftwood Search Service
type DriftwoodSearchServiceClient interface {
	SearchDriftwood(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type driftwoodSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriftwoodSearchServiceClient(cc grpc.ClientConnInterface) DriftwoodSearchServiceClient {
	return &driftwoodSearchServiceClient{cc}
}

func (c *driftwoodSearchServiceClient) SearchDriftwood(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, DriftwoodSearchService_SearchDriftwood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriftwoodSearchServiceServer is the server API for DriftwoodSearchService service.
// All implementations must embed UnimplementedDriftwoodSearchServiceServer
// for forward compatibility.
//
// Driftwood Search Service
type DriftwoodSearchServiceServer interface {
	SearchDriftwood(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedDriftwoodSearchServiceServer()
}

// UnimplementedDriftwoodSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriftwoodSearchServiceServer struct{}

func (UnimplementedDriftwoodSearchServiceServer) SearchDriftwood(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDriftwood not implemented")
}
func (UnimplementedDriftwoodSearchServiceServer) mustEmbedUnimplementedDriftwoodSearchServiceServer() {
}
func (UnimplementedDriftwoodSearchServiceServer) testEmbeddedByValue() {}

// UnsafeDriftwoodSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriftwoodSearchServiceServer will
// result in compilation errors.
type UnsafeDriftwoodSearchServiceServer interface {
	mustEmbedUnimplementedDriftwoodSearchServiceServer()
}

func RegisterDriftwoodSearchServiceServer(s grpc.ServiceRegistrar, srv DriftwoodSearchServiceServer) {
	// If the following call pancis, it indicates UnimplementedDriftwoodSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriftwoodSearchService_ServiceDesc, srv)
}

func _DriftwoodSearchService_SearchDriftwood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriftwoodSearchServiceServer).SearchDriftwood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriftwoodSearchService_SearchDriftwood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriftwoodSearchServiceServer).SearchDriftwood(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriftwoodSearchService_ServiceDesc is the grpc.ServiceDesc for DriftwoodSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriftwoodSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dws.DriftwoodSearchService",
	HandlerType: (*DriftwoodSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchDriftwood",
			Handler:    _DriftwoodSearchService_SearchDriftwood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dws_ml_service.proto",
}
