FROM node:18-alpine

# Add global node path to ensure binaries are found
ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm i -g pnpm
RUN pnpm install

# Copy the rest of the application code
COPY * .

EXPOSE ${DWS_EXT_WEBAPP_PORT}

CMD ["npm", "run", "dev"]