# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.grpc_service.dws_ml_server_pb2 as dws__ml__server__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dws_ml_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriftwoodSearchServiceStub(object):
    """Driftwood Search Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchDriftwood = channel.unary_unary(
                '/dws.DriftwoodSearchService/SearchDriftwood',
                request_serializer=dws__ml__server__pb2.SearchRequest.SerializeToString,
                response_deserializer=dws__ml__server__pb2.SearchResponse.FromString,
                _registered_method=True)


class DriftwoodSearchServiceServicer(object):
    """Driftwood Search Service
    """

    def SearchDriftwood(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriftwoodSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchDriftwood': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDriftwood,
                    request_deserializer=dws__ml__server__pb2.SearchRequest.FromString,
                    response_serializer=dws__ml__server__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dws.DriftwoodSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dws.DriftwoodSearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriftwoodSearchService(object):
    """Driftwood Search Service
    """

    @staticmethod
    def SearchDriftwood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dws.DriftwoodSearchService/SearchDriftwood',
            dws__ml__server__pb2.SearchRequest.SerializeToString,
            dws__ml__server__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
