# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dws_ml_server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dws_ml_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64ws_ml_server.proto\x12\x03\x64ws\"\xa1\x01\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x30\n\x07\x66ilters\x18\x02 \x03(\x0b\x32\x1f.dws.SearchRequest.FiltersEntry\x12\x1f\n\x17include_recommendations\x18\x03 \x01(\x08\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"e\n\x0eSearchResponse\x12#\n\x07results\x18\x01 \x03(\x0b\x32\x12.dws.DriftwoodItem\x12.\n\x0frecommendations\x18\x02 \x03(\x0b\x32\x15.dws.DriftwoodSummary\"Y\n\rDriftwoodItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nimage_path\x18\x02 \x01(\t\x12(\n\x08metadata\x18\x03 \x01(\x0b\x32\x16.dws.DriftwoodMetadata\"R\n\x10\x44riftwoodSummary\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nimage_path\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\"\x83\x02\n\x11\x44riftwoodMetadata\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x01\x12\r\n\x05\x63olor\x18\x03 \x01(\t\x12\x0f\n\x07texture\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x1a\n\x12weather_conditions\x18\x06 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x07 \x01(\t\x12\x18\n\x10\x64ominant_species\x18\x08 \x01(\t\x12\x19\n\x11\x64istance_to_water\x18\t \x01(\x01\x12\x13\n\x0btime_of_day\x18\n \x01(\t\x12\x13\n\x0btemperature\x18\x0b \x01(\x01\x12\x10\n\x08humidity\x18\x0c \x01(\x01\x32T\n\x16\x44riftwoodSearchService\x12:\n\x0fSearchDriftwood\x12\x12.dws.SearchRequest\x1a\x13.dws.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dws_ml_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST_FILTERSENTRY']._loaded_options = None
  _globals['_SEARCHREQUEST_FILTERSENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=29
  _globals['_SEARCHREQUEST']._serialized_end=190
  _globals['_SEARCHREQUEST_FILTERSENTRY']._serialized_start=144
  _globals['_SEARCHREQUEST_FILTERSENTRY']._serialized_end=190
  _globals['_SEARCHRESPONSE']._serialized_start=192
  _globals['_SEARCHRESPONSE']._serialized_end=293
  _globals['_DRIFTWOODITEM']._serialized_start=295
  _globals['_DRIFTWOODITEM']._serialized_end=384
  _globals['_DRIFTWOODSUMMARY']._serialized_start=386
  _globals['_DRIFTWOODSUMMARY']._serialized_end=468
  _globals['_DRIFTWOODMETADATA']._serialized_start=471
  _globals['_DRIFTWOODMETADATA']._serialized_end=730
  _globals['_DRIFTWOODSEARCHSERVICE']._serialized_start=732
  _globals['_DRIFTWOODSEARCHSERVICE']._serialized_end=816
# @@protoc_insertion_point(module_scope)
