FROM python:3.10-slim

# Env variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    LOGURU_LEVEL=DEBUG \
    PYTHONPATH=/app

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy application files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r ./app/requirements.txt

# Install watchdog for hot reload
RUN pip install watchdog

# Expose the gRPC port
EXPOSE ${PORT}

# Start the application with hot-reload enabled
CMD ["watchmedo", "auto-restart", "--patterns=*.py", "--recursive", "python", "app/main.py"]